### ISSUE TITLE
TTLCache - similar, but different?

### ISSUE THREAD

**Issue by astronautas** [datarootsio/expiring-lru-cache#7]
Hey, I recall using [TTLCache](https://cachetools.readthedocs.io/en/latest/#cachetools.TTLCache) from cachetools before to achieve similar outcomes. I assume the functional difference is that TTLCache timer is per-item, whilst expiring cache timer is per-function?

**Comment by murilo-cunha** [comment]
Yes, I believe that's correct 😇
