### ISSUE TITLE
How to get cache_info

### ISSUE THREAD

**Issue by xingzhao-tt** [datarootsio/expiring-lru-cache#8]
Hi, 

Use functools.lru_cache, we can use cache_info() to get cache hit/miss/size info, but use expiring_lru_cache,  cannot call cache_info() function.

**Comment by bart6114** [comment]
Hi @xingzhao-tt 👋  This is now available in the latest release, it exposes the `cache_info` from functools.lru_cache and would work exactly the same as you would expect it to work with functools. Note that it only contains data from the latest non-expired cache instance.
